services:
  db:
    image: mysql:8.0
    container_name: softball_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: softball_db
      MYSQL_USER: zeb
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - 3306:3306